apiVersion: v1
kind: Pod
metadata:
  name: log-generator
  #namespace: laptop-local
  labels:
    app: log-generator
spec:
  containers:
    - name: log-generator
      image: quay.io/dstorck/log_generator:latest
      ports:
      - containerPort: 8080
